version: '3.7'

services:
  api:
    stdin_open: true
    container_name: api
    build: 
      context: .
      dockerfiel: Dockerfile-arm32v7
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    ports:
      - "8008:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - network
  db:
    image: arm32v7/postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    networks:
      - network
  
  nginx:
    image: arm32v7/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - network


  adminer:
    image: arm32v7/adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge